# Site settings
title: Raunak Kathuria
email: raunakkathuria@gmail.com
description: >
  Driven by passion for web designing - Believe in simple
  yet elegant design.
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'http://raunakkathuria.com' # the base hostname & protocol for your site
github_username:  raunakkathuria

# Build settings
markdown: kramdown
